name: 'ci'
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Restore
        run: dotnet restore ./untitled.sln
      - name: Build
        run: dotnet build ./untitled.sln
